spring:
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:moviesdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2.console.enabled: true
auth0.audience: https://booking-api.com
auth0.domain: dev-tjo9gany.us.auth0.com
spring.security.oauth2.resourceserver.jwt.issuer-uri: https://${auth0.domain}/